### ISSUE TITLE
Infer Table Schema from CSV (when uploading) and use in schema editor

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#17]
If a file is selected we want to infer a frictionless style object that we can use for the metadata. Suggest using data.js and fixing this issue https://github.com/datopian/data.js/issues/49

## Acceptance

* [x] When a CSV file is selected and it is tabular file the resource object in the state is updated with correct meta and inferred schema
  * [x] Plus sample data e.g. first, say 20-30 rows is put in `sample` attribute.
* [x] this works for xlsx (first sheet)
* [ ] ~~When a linked file is chosen we infer core meta from url and *try* to load data (if CORs issue then just give up (maybe flag an error)~~ MOVED to #32

**Comment by anuveyatsu** [comment]
I'm planning to work in this next as https://github.com/datopian/data.js/pull/68 is to be merged soon. I can start working using `feature/open-from-uploaded-file` branch.

cc @rufuspollock

**Comment by mariorodeghiero** [comment]
Some updates for this issue on this PR https://github.com/datopian/datapub/pull/26

**Comment by anuveyatsu** [comment]
When using Excel files, we have some issues:

- we can't get sample data but only full data so your browser can slow down as we automatically load all rows into memory
- the same issue when inferring schema

**Comment by rufuspollock** [comment]
FIXED. All working.
