### ISSUE TITLE
[resource] Add multiple resources at once

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#22]
See #1 for background.

![](https://camo.githubusercontent.com/6bf25ce8caab1f6fc834e61fc81fc815a94158d7/68747470733a2f2f692e696d6775722e636f6d2f415a3744354a512e706e67)

## Acceptance

TODO

## Tasks

**Comment by rufuspollock** [comment]
@mariorodeghiero could you fill out the issue with acceptance and tasks a bit.

**Comment by mariorodeghiero** [comment]
@rufuspollock @lgilies this issue is duplicate? 
check this one https://github.com/datopian/datapub/issues/23

**Comment by rufuspollock** [comment]
DUPLICATE of #23.
