### ISSUE TITLE
Refactor due to recent updates in ckan-client-js

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/datapub#27]
Refactor due to recent updates in ckan-client-js so we can create/update resources + push to blob.

Acceptance

- [x] Refactor react code to use the recent updates in the SDK

Tasks

- [x] Refactor react code to use create resource
- [x] Refactor code to update resource
- [x] Refactor code to push to blob

**Comment by mariorodeghiero** [comment]
Blocked https://github.com/datopian/data.js/issues/86

cc: @rufuspollock @anuveyatsu

**Comment by rufuspollock** [comment]
FIXED. This is all done.
