### ISSUE TITLE
Pattern for creating custom publish flows on top of DataPub

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#33]
We already have an example where we need to customize the publish flow:

>  Also, a resource can be restricted (eg, public vs private) but it is something custom and it is missing in DataPub. Eg: "restricted": "{\"level\": \"public\"}"

We need custom publish flows per client. e.g. this feature is specific to a given ckan deployment. Rather than modify ckanext-blob-storage we basically need to be able to install a custom React app.

`ckanext-blob-storage` should have NO dependency on datapub.js. What we want is to pass a React app into CKAN or rather `ckanext-blob-storage`.

You create 

```
ckanext-publish-{client-name}
```

And inside of this is a React app using components from DataPub.js.

OR  we have a way inside `ckanext-blob-storage` to point to a react app.

**Comment by mariorodeghiero** [comment]
@rufuspollock now we have the [datapub-gdx](https://github.com/datopian/datapub-gdx) working with multiple files. I think we can close this issue?

**Comment by rufuspollock** [comment]
DUPLICATE of #62
