### ISSUE TITLE
[resource] Remove 2 step process and show schema editor

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#39]
## Current setup

2 stages and you have to click between.

![image](https://user-images.githubusercontent.com/180658/93762983-e16e4d00-fc10-11ea-9c1b-c6cfca98d293.png)

Issue is that UX is bad as people don't see schema editor.

## Wanted

Show both metadata editor and schema editor at same time one below the other. Something like this without the 1 and 2:

![image](https://user-images.githubusercontent.com/180658/93762983-e16e4d00-fc10-11ea-9c1b-c6cfca98d293.png)
![image](https://user-images.githubusercontent.com/180658/93763948-91908580-fc12-11ea-8f79-8f3664f65fa2.png)
![image](https://user-images.githubusercontent.com/180658/93764716-e385db00-fc13-11ea-8b37-d2234262d29e.png)

**Comment by mariorodeghiero** [comment]
sorry, the commits above should be for the issue #29 .

**Comment by mariorodeghiero** [comment]
@rufuspollock I already have the solution for this issue in my machine, but I will push the PR after the changes to fix redirect are done because will have some conflicts.

**Comment by mariorodeghiero** [comment]
FIXED. You can check in this PR https://github.com/datopian/datapub/pull/45
