### ISSUE TITLE
New CKAN extension `ckanext-datapub` for integrating DataPub based apps into CKAN v2 workflow

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#63]
There are two areas of integration:

* Dataset creator (and editor)
* Resource editor

DataPub based app could replace one or both of these. (Note DataPub based app may have other steps that CKAN does not currently have but we are jus focusing on current CKAN v2 end).

We need a CKAN extension that can replace one or both of Dataset editing and Resource editing by handing off to a React app. The React app *source code* will likely be located elsewhere (need to specific its build state for integration).

## Acceptance

* [x] `ckanext-datapub` exists - https://github.com/datopian/ckanext-datapub
* [x] Can override one or both of existing Dataset and/or Resource flow with React app (for first effort could just hard-code resource editor since we already have that working in ckanext-blob-storage and leave dataset for later) - **tested by @mariorodeghiero with one project**
* [x] Clear instructions on how to configure the React app to use (and how that React app should be built) - https://github.com/datopian/ckanext-datapub#installation
* [x] Clear instructions to React app builders of what variables will be passed from CKAN - https://github.com/datopian/ckanext-datapub/commit/d0e273844b0d86f8301f563acc49c08d2aeb69cd

**Comment by rufuspollock** [comment]
@anuveyatsu has made progress on this here: https://github.com/datopian/ckanext-datapub

@anuveyatsu is this ready to be trialled?

**Comment by anuveyatsu** [comment]
@rufuspollock yes, I've made some fixes today and it should be good to trial :+1:

**Comment by anuveyatsu** [comment]
We have last acceptance criteria leftover before we can close this issue @rufuspollock @mariorodeghiero

**Comment by mariorodeghiero** [comment]
@anuveyatsu Now I can see the variable in the spect element and I check with Patricio, I need to run the giftless and authz-service separately. 
cc: @rufuspollock 

![Screenshot from 2020-10-19 17-12-42](https://user-images.githubusercontent.com/24671133/96506636-5ba0ea00-122e-11eb-993a-693f75b0e2ea.png)

**Comment by anuveyatsu** [comment]
I'm closing this issue as FIXED as all tasks and acceptance criteria are met.

@mariorodeghiero as we've discussed the issue you're facing is the project specific.
