### ISSUE TITLE
Upload of large files is failing 

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/datapub#78]
This issue is related https://github.com/datopian/datapub-nhs/issues/14 

After some analysis and tests to upload large files, the root cause to upload large files happens because of the code below. 
**Note:** After removed this part, I tested with 600Mb and 1.gb and it works very well.
```
try {
	const rowStream = await resource.rows({ size: 20, keyed: true })
	resource.descriptor.sample = await toArray(rowStream)
	await resource.addSchema()
} catch (e) {
      console.error(e)
}
```

**Why exist the [try-catch above](https://github.com/datopian/datapub/blob/master/src/components/Upload/index.jsx#L32)?** The code above is necessary to be able to render data into the table schema component, but for some reason is consuming a lot of memory, and sometimes crash the browser with no errors on the console dev tools. 

**Another error:** in one of our tests we also try to upload a different format and it failed, and showed a parser error, as you can see on the screenshot below.

![image](https://user-images.githubusercontent.com/24671133/99810320-53381980-2b22-11eb-90a9-d8298e69ad5b.png)

**Comment by rufuspollock** [comment]
@mariorodeghiero a likely guess is that rows call is reading the *whole*  file. Have we checked that only reads a small part of the file rather than the whole file.

**Comment by mariorodeghiero** [comment]
I think yes, this was developed at the beginning of the project, and we did a lot of changes in the frinctionless.js library @risenW  is checking about it. 
maybe @anuveyatsu knows something to add here too.

**Comment by risenW** [comment]
> @mariorodeghiero a likely guess is that rows call is reading the _whole_ file. Have we checked that only reads a small part of the file rather than the whole file.

@rufuspollock This is my guess as well, I'm jumping on this issue now
