### ISSUE TITLE
Publish to npm as datapub (and make datopian an owner)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/datapub#80]
## Acceptance

* [x] Published on datapub __Done__ https://www.npmjs.com/package/datapub
* [x] datopian user is an owner __Done__ @risenW is registered as the owner
* [x] README updated where relevant to reference the published package rather than git link (e.g. in `yarn add` __Done__ See updated [Readme](https://github.com/datopian/datapub#getting-started)

**Comment by risenW** [comment]
@rufuspollock This is done

**Comment by rufuspollock** [comment]
@risenW great - let's close the issue 😄
